services:
  mongodb:
      image:mongodb/mongodb-community-server:latest
      container_name: reverent_pare
      restart: unless-stopped
      ports:
        - "27017:27017"
      volumes:
        - mongodb:/data/db
      environment:
            MONGO_INITDB_ROOT_USERNAME: nraboy
            MONGO_INITDB_ROOT_PASSWORD: password1234
volumes:
  mongodb:
      external: true